crud/books/urls.py
from django.urls import path

from . import views

app_name = 'books'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create', views.CreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/', views.DeleteView.as_view(), name='delete'),
    path('create_book/', views.create_book, name='create_book'),
    path('update_book/', views.update_book, name='update_book'),
    path('delete_book/', views.delete_book, name='delete_book'),
]

crud/crud/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('books/', include('books.urls')),
]

crud/books/models.py
from django.db import models
from django.urls import reverse

class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('book_edit', kwargs={'pk': self.pk})

crud/books/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Book

class IndexView(generic.ListView):
    template_name = 'books/index.html'
    model = Book

class DetailView(generic.DetailView):
    model = Book
    template_name = 'books/detail.html'

class CreateView(CreateView):
    model = Book
    fields = ['name', 'pages']
    template_name = 'books/create.html'
    success_url = reverse_lazy('books:index')

class UpdateView(generic.DetailView):
    model = Book
    template_name = 'books/update.html'

class DeleteView(DeleteView):
    model = Book
    template_name = 'books/delete.html' 

def create_book (request):
    book = Book(name = request.POST['bookName'], pages = request.POST['bookPages'])
    book.save()
    return HttpResponseRedirect(reverse('books:index'))

def update_book (request):
    c = Book.objects.filter(name = request.POST['bookName'])
    c.delete()
    book = Book(name = request.POST['bookName'], pages = request.POST['bookPages'])
    book.save()
    return HttpResponseRedirect(reverse('books:index'))

def delete_book (request):
    c = Book.objects.filter(name = request.POST['nameDelete'])
    c.delete()
    return HttpResponseRedirect(reverse('books:index'))

crud/books/templates/books/book_list.html
<h1>Books</h1>

<table border="1">
<thead>
    <tr>
    <th>Name</th>
    <th>Pages</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for book in object_list %}
    <tr>
    <td>{{ book.name }}</td>
    <td>{{ book.pages }}</td>
    <td><a href="{% url "books:show" book.id %}">view</a></td>
    <td><a href="{% url "books:edit" book.id %}">edit</a></td>
    <td><a href="{% url "books:delete" book.id %}">delete</a></td>
    </tr>
    {% endfor %}
</tbody>
</table>

<a href="{% url "book:create" %}">New</a>

crud/books/templates/books/create.html
<script>
    function func () {
         alert ("Hello");
    }
</script>
<h1>Book Create</h1>
<form method="post">
{% csrf_token %}
    <input name="name">
    <br />
    <input name="pages">
    <br />
    <button onclick="func()">Click</button>

    <input type="submit" value="create_book">
</form>

crud/books/templates/books/delete.html
<h1>Book Delete</h1>
<form action="{% url 'books:delete_book' %}" method="post">
   {% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
   <input hidden name="nameDelete" value='{{ object.name }}'>
   <input type="submit" value="book_delete" />
</form>

crud/books/templates/books/detail.html
<h1>Book Details</h1>
<h2>Name: {{object.name}}</h2>
Pages: {{ object.pages }}

crud/books/templates/books/index.html
<h1>Books</h1>

<table border="1">
<thead>
    <tr>
    <th>Name</th>
    <th>Pages</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for book in object_list %}
    <tr>
    <td>{{ book.name }}</td>
    <td>{{ book.pages }}</td>
    <td><a href="{% url "books:detail" book.id %}">view</a></td>
    <td><a href="{% url "books:update" book.id %}">edit</a></td>
    <td><a href="{% url "books:delete" book.id %}">delete</a></td>
    </tr>
    {% endfor %}
</tbody>
</table>

<a href="{% url 'books:create' %}">New</a>

crud/books/templates/books/show.html
<h1>Books</h1>

<table border="1">
<thead>
    <tr>
    <th>Name</th>
    <th>Pages</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for book in object_list %}
    <tr>
    <td>{{ book.name }}</td>
    <td>{{ book.pages }}</td>
    <td><a href="{% url "books:show" book.id %}">view</a></td>
    <td><a href="{% url "book_edit" book.id %}">edit</a></td>
    <td><a href="{% url "book_delete" book.id %}">delete</a></td>
    </tr>
    {% endfor %}
</tbody>
</table>

<a href="{% url "book_new" %}">New</a>

crud/books/templates/books/update.html
<h1>Book Update</h1>
<h1>{{ bookVal.name }}</h1>
<form action="{% url 'books:update_book' %}" method="post">
{% csrf_token %}
    <input name="bookName" value='{{ object.name }}'>
    <input name="bookPages" value='{{ object.pages }}'>
    <input type="submit" value="update_book" />
</form>